include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error Rules
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - no_duplicate_case_values
    - prefer_void_to_null
    - use_key_in_widget_constructors

    # Style Rules
    - always_declare_return_types
    - avoid_empty_else
    - avoid_unnecessary_containers
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - require_trailing_commas
    - sort_child_properties_last
    - use_super_parameters

    # Pub Rules
    - depend_on_referenced_packages

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore
